# Generated by Django 3.2 on 2022-12-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tweet',
        ),
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.tweet'),
        ),
    ]
