# Generated by Django 3.2 on 2022-12-29 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20221229_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mark',
            new_name='Mark_tweet',
        ),
        migrations.CreateModel(
            name='Mark_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_value', models.IntegerField()),
                ('comment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
